"""Module-level constants shared across analyzer sub-modules."""

DEFAULT_R_VECTOR: dict[str, float] = {
    "trust": 0.5,
    "warmth": 0.5,
    "stability": 0.5,
    "openness": 0.5,
    "initiative": 0.5,
    "reciprocity": 0.5,
    "repair": 0.5,
    "alignment": 0.5,
    "dependence": 0.5,
    "engagement": 0.5,
}

# --- Relationship state deltas ---
APPRECIATION_TRUST_DELTA = 0.05
APPRECIATION_WARMTH_DELTA = 0.08
APPRECIATION_RECIPROCITY_DELTA = 0.06
CONNECTION_OPENNESS_DELTA = 0.06
CONNECTION_ENGAGEMENT_DELTA = 0.05
CONNECTION_RECIPROCITY_DELTA = 0.03
NEGATIVE_STABILITY_DELTA = -0.05
NEGATIVE_RECIPROCITY_DELTA = -0.04

# --- Proactive timing (seconds) ---
PROACTIVE_PROGRESS_NUDGE_TRIGGER = 1800
PROACTIVE_PROGRESS_NUDGE_WINDOW = 7200
PROACTIVE_GROUNDED_CHECKIN_TRIGGER = 900
PROACTIVE_GROUNDED_CHECKIN_WINDOW = 3600
PROACTIVE_LIGHT_CHECKIN_TRIGGER = 3600
PROACTIVE_LIGHT_CHECKIN_WINDOW = 14400
PROACTIVE_IDLE_OVERRIDE_TRIGGER = 600

# --- Controller spacing (seconds) ---
SECOND_TOUCH_RECENTER_DELAY = 6300
SECOND_TOUCH_WATCH_DELAY = 4050

# --- Strategy diversity ---
STRATEGY_DIVERSITY_ENTROPY_THRESHOLD = 0.8
STRATEGY_DOMINANT_COUNT_MINIMUM = 3

# --- Memory limits ---
WORKING_MEMORY_HISTORY_LIMIT = 6
EPISODIC_MEMORY_HISTORY_LIMIT = 8
SEMANTIC_CONCEPT_LIMIT = 12
RELATIONAL_MEMORY_LIMIT = 6
REFLECTIVE_MEMORY_LIMIT = 4

# --- Evaluation thresholds ---
QUALITY_VIOLATION_PENALTY = 0.35
LLM_FAILURE_PENALTY = 0.2
QUALITY_WATCH_PENALTY = 0.4
SYSTEM3_WATCH_PENALTY = 0.1
LENGTH_BLOAT_MIN_DELTA = 12
LENGTH_BLOAT_MULTIPLIER = 1.75
LENGTH_BLOAT_SLOPE_THRESHOLD = 4.0
LEXICAL_DIVERSITY_DROP_THRESHOLD = 0.2
LEXICAL_DIVERSITY_SLOPE_THRESHOLD = -0.05
